# Site settings
title: Do they get tech?
email: fraser.scott@gmail.com
description: > 
  Politicians, advisors and the media have a tremendous influence on policies that affect technology and technology-related industries. But technology is a vast, rapidly changing and surprisingly unintuitive field. It is changing the way we communicate, conduct business, learn, heal the sick, and generally progress as a civilisation. Which decision makers and influencers actually have a basic grasp of this increasingly important and pervasive field?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dotheyget.tech" # the base hostname & protocol for your site
#url: "http://localhost:4000"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
